name: Basic experiment runs

on:
  workflow_dispatch:
    inputs:
        topology:
            description: 'Network topology to use in experiment'
            required: false
            default: 'abilene'
            type: string

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    IMAGE_NAME: multi-tier

jobs:   
    run-st-req-rate:
        runs-on: self-hosted
        steps:
          - name: Pull Docker image
            run: docker pull ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          - name: Run st_req_rate experiment and upload result
            run: |
              mkdir -p ~/actions-artifacts
              mkdir -p ~/actions-artifacts/sim_outputs
              docker run --rm -v ~/actions-artifacts/sim_outputs:/multi-tier/sim_outputs ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest python3 -m simulator.sim_runner -e=st_req_rate -t=${{ inputs.topology }} --config_local=./sim_configs/ct_configs/st_req_rate_config.json
          - uses: actions/upload-artifact@v3
            with:
              name: st_req_rate
              path: ~/actions-artifacts/sim_outputs/st_req_rate*
    run-st-cache-size:
        runs-on: self-hosted
        steps:
          - name: Pull Docker image
            run: docker pull ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          - name: Run st_cache_size experiment and upload result
            run: |
                mkdir -p ~/actions-artifacts
                mkdir -p ~/actions-artifacts/sim_outputs
                docker run --rm -v ~/actions-artifacts/sim_outputs:/multi-tier/sim_outputs ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest python3 -m simulator.sim_runner -e=st_cache_size -t=${{ inputs.topology }} --config_local=./sim_configs/ct_configs/st_cache_size_config.json
          - uses: actions/upload-artifact@v3
            with:
                name: st_cache_size
                path: ~/actions-artifacts/sim_outputs/st_cache_size*