name: Basic experiment runs

on:
  workflow_dispatch:
    inputs:
        topology:
            description: 'Network topology to use in experiment'
            required: false
            default: 'abilene'
            type: string

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    IMAGE_NAME: multi-tier

jobs:
    pull-docker-image:
      runs-on: self-hosted
      steps:
        - name: Pull Docker image
          run: docker pull ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
    run-st-req-rate:
        runs-on: self-hosted
        steps:
          - name: Run st_req_rate experiment and upload result
            run: |
              mkdir -p ~/artifacts
              mkdir -p ~/artifacts/sim_outputs
              docker run -v ~/artifacts/sim_outputs:/multi-tier/sim_outputs ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest python3 -m simulator.sim_runner -e=st_req_rate -t=${{ inputs.topology }} --config_local=./sim_configs/ct_configs/st_req_rate_config.json
              tar -czf ~/artifacts/st_req_rate.tar.gz ~/artifacts/sim_outputs
          - uses: actions/upload-artifact@v3
            with:
              name: st_req_rate
              path: ~/artifacts/st_req_rate.tar.gz
    run-st-cache-size:
        runs-on: self-hosted
        steps:
          - name: Run st_cache_size experiment and upload result
            run: |
                mkdir -p ~/artifacts
                mkdir -p ~/artifacts/sim_outputs
                docker run -v ~/artifacts/sim_outputs:/multi-tier/sim_outputs ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest python3 -m simulator.sim_runner -e=st_cache_size -t=${{ inputs.topology }} --config_local=./sim_configs/ct_configs/st_cache_size_config.json
                tar -czf ~/artifacts/st_cache_size.tar.gz ~/artifacts/sim_outputs
          - uses: actions/upload-artifact@v3
            with:
                name: st_cache_size
                path: ~/artifacts/st_cache_size.tar.gz