name: Custom Experiment Run w/ URL Config

on:
  workflow_dispatch:
    inputs:
        name:
            description: 'Experiment name'
            required: true
            type: string
        topology:
            description: 'Network topology to use in experiment'
            required: true
            default: 'abilene'
            type: string
        config_url:
            description: 'URL that directs to raw JSON for experiment config'
            required: true
            type: string
        runner:
            description: 'Which runner to send the job to'
            required: true
            type: choice
            options:
            - ubuntu-latest
            - self-hosted

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    IMAGE_NAME: multi-tier

jobs:   
    run-custom-experiment:
        runs-on: ${{ inputs.runner }}
        steps:
          - name: Pull Docker image
            run: docker pull ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          - name: Run experiment and upload result
            run: |
              mkdir -p ~/actions-artifacts
              mkdir -p ~/actions-artifacts/sim_outputs
              docker run --rm -v ~/actions-artifacts/sim_outputs:/multi-tier/sim_outputs ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest python3 -m simulator.sim_runner -e=${{ inputs.name }} -t=${{ inputs.topology }} --config_url=${{ inputs.config_url }}
          - uses: actions/upload-artifact@v3
            with:
              name: experiment-outputs
              path: ~/actions-artifacts/sim_outputs/${{ inputs.name }}*