name: Custom Experiment Run w/ URL Config

on:
  workflow_dispatch:
    inputs:
        runner:
            description: 'Which runner to send the job to'
            required: true
            type: choice
            options:
            - ubuntu-latest
            - self-hosted
        name:
            description: 'Experiment name'
            required: true
            type: string
        topology:
            description: 'Network topology to use in experiment'
            required: true
            type: string
            default: 'abilene'
        config_url:
            description: 'URL that directs to raw JSON for experiment config'
            required: true
            type: string
        x_label:
            description: 'Parameter on the x-axis of output plot'
            required: false
            type: string
        metric:
            description: 'Metric on the y-axis of output plot'
            required: false
            type: string
        curve_label:
            description: '(Optional) Parameter to iterate different curves on the output plot'
            required: false
            type: string
            default: ''

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    IMAGE_NAME: multi-tier
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:   
    run-custom-experiment:
        runs-on: ${{ inputs.runner }}
        timeout-minutes: 1200
        steps:
          - name: Pull Docker image
            run: docker pull ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
          - name: Run experiment
            run: |
              mkdir -p ~/actions-artifacts
              mkdir -p ~/actions-artifacts/sim_outputs
              docker run --rm -v ~/actions-artifacts/sim_outputs:/multi-tier/sim_outputs ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }} python3 -m simulator.sim_runner -e=${{ inputs.name }} -t=${{ inputs.topology }} --config_url=${{ inputs.config_url }}
          - name: Plot results
            continue-on-error: true
            run: docker run --rm -v ~/actions-artifacts/sim_outputs:/multi-tier/sim_outputs ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }} python3 -m data_analysis.custom_plotter -e=${{ inputs.name }} -t=${{ inputs.topology }} --config_url=${{ inputs.config_url }} --x_label=${{ inputs.x_label }} --metric=${{ inputs.metric }} --curve_label=${{ inputs.curve_label }}
          - name: Get current date and time
            id: date-time
            run: echo "DATETIME=$(date +'%Y-%m-%d_%H-%M')" >> "$GITHUB_OUTPUT"
          - uses: actions/upload-artifact@v3
            with:
              name: ${{ inputs.name }}-${{ inputs.topology }}-outputs-${{ steps.date-time.outputs.DATETIME }}
              path: ~/actions-artifacts/sim_outputs/${{ inputs.name }}_${{ inputs.topology }}*