name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: multi-tier

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  run-experiments:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Pull Docker image
        run: docker pull ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
      - name: Run sample experiment and upload result
        run: |
          mkdir -p ~/artifacts
          mkdir -p ~/artifacts/sim_outputs
          docker run -v ~/artifacts/sim_outputs:/multi-tier/sim_outputs ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest python3 -m simulator.sim_runner
          tar -czf ~/artifacts/sim_outputs.tar.gz ~/artifacts/sim_outputs
      - uses: actions/upload-artifact@v4
        with:
          name: sim-outputs
          path: ~/artifacts/sim_outputs.tar.gz
          

